### ISSUE TITLE
Having some trouble with whitespace

### ISSUE THREAD

**Issue by da-am** [Ahuge/NukeParser#4]
Hi, I stumbled upon your parser (great btw) and I'm just getting into the wonderful world of parsing nuke files outside of nuke. I had a question. I'm finding that white space in a knob value will exclude the knob from the raw node list entirely. I can't quite place why that is. Gut says its in the node_open/close regex but I don't use regex a lot nor am I classically trained in python (still learning).

I know this is from a long time ago and some of it doesn't work in Python3 but I was wondering if there was a simple answer to that question? 
Thanks!

**Comment by Ahuge** [comment]
Hi da-am,

I am sorry, I have neglected this for so long. I would bet that very little of this actually works.

My first thought would be the KNOB_KV regex, because it looks quite basic.
https://github.com/Ahuge/NukeParser/blob/97a37883f5ccf030da319d21c5f80cfd6113df49/parse.py#L7

It looks like I am just looking for any set of word characters, a single space, and then more word characters.
If I was to write a regex in the future that tried to do this, I would probably want to expand the value portion of that regex, support adding quotes around values containing spaces like you mention.


______

You may have better luck looking at a [stunning-barnacle](https://github.com/Ahuge/stunning-barnacle) which was a more recent look at this problem.
It attempts to build a BNF grammar to start solving this problem, see [grammar.bnf](https://github.com/Ahuge/stunning-barnacle/blob/master/stunning/grammar.bnf) for the base grammar and [roto.bnf](https://github.com/Ahuge/stunning-barnacle/blob/master/stunning/roto.bnf) for the example of how I started implementing some of the more complex grammars like Roto nodes.

Now, I know that stunning-barnacle doesn't properly support some of the more advanced node types like `Roto` and `Tracker`.
I wish I had more time to dig back into this problem, I really enjoyed the parser level language problems.

If you want to continue along either this repo or the stunning-barnacle one, I can give you commit access to it (or just merge in any PRs if you'd prefer).

Thanks
-Alex

**Comment by da-am** [comment]
No worries! It actually has started me down a path I was hoping to go - so perfect for me. I'll look into the regex of the NODE_KV. Thanks for the hint! 
I tried stunning-barnacle because it does look a bit more robust but I have zero knowledge of bnf / grammer for parsers and its a bit over my head. Also, when I ran it to see if I could do something with it I ran into "Illegal character" warnings on the first line of my nk script. Looks really really interesting though. I may come back to it and see what I'm doing wrong. 

For now, this project is perfect as I am just looking through nuke files and pulling out Write nodes to send out to a farm. So again, many thanks! If I can fix some things up I'll send in some merge PRs in the future.
Anthony
